services:
  mongodb:
    image: mongo:8.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - reciptile-mongodb:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  reciptile-mongodb:
